---
blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/demaconsulting/CanvasNet
    about: Read the documentation for CanvasNet
  - name: 💬 Discussions
    url: https://github.com/demaconsulting/CanvasNet/discussions
    about: Ask questions and discuss with the community
